config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end

  resources :foods

  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'

  post '/recipe/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

  get '/general_shopping_list', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :destroy
  has_and_belongs_to_many :foods, join_table: :recipe_foods

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 50 }
  validates :preparation_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :description, presence: true, length: { minimum: 10, maximum: 500 }
  validates :public, inclusion: { in: [true, false] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  include RecipesHelper

  def index
    @recipes = Recipe.includes(:recipe_foods).where(user_id: current_user.id)
    notice_message
  end

  def show
    notice_message
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
    respond_to do |format|
      format.html { render :new }
      format.js { render :new }
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    @recipe.public = params[:public] == 'Public'

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update; end

  def destroy
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if can? :destroy, @recipe
        @recipe.destroy
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to recipes_path, alert: 'Recipe was not deleted.' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def public_recipes
    @public_recipes = User.includes(:recipes,
                                    :recipe_foods).where(recipes: { public: true }).order('recipes.created_at DESC')
  end

  def toggle_public
    @recipe = Recipe.find(params[:id])
    @recipe.toggle!(:public)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { redirect_to recipes_path, alert: 'Recipe was not updated.' }
        format.json { render json: @recipe.errors, status: unprocessable_entity }
      end
    end
  end

  def general_shopping_list
    @shopping_list = Food.includes(:recipe_foods).where(recipe_foods: { recipe_id: nil })
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def notice_message
    url = Rails.application.routes.recognize_path(request.referrer)
    flash.delete(:notice) unless %w[index show new edit update
                                    destroy].include?(url[:action]) &&
                                 (url[:controller] == 'recipes' || url[:controller] == 'recipe_foods')
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: @recipe, url: recipes_path, local: true) do |form| %>
  <div class = "mt-4 p-2">
    <%= select_tag(:public, options_for_select([['Select Status', 'Status'], ['Public', 'Public'], ['Private', 'Private']], 'Status'),
      class: 'form-select')
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:status].first %>
        </p>
    <% end %>
  </div>

	<div class = "mt-2 p-2">
		<%= form.text_field :name,
        autofocus: true, 
        autocomplete: 'name', 
        placeholder: 'New recipe name', 
        class: 'form-control' 
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:name].first %>
        </p>
    <% end %>
	</div>

  <div class = "mt-2 p-2">
    <%= form.number_field :preparation_time,
        autofocus: true,
        autocomplete: 'preparation_time',
        placeholder: 'Preparation time in hour(s)',
        class: 'form-control'
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:preparation_time].first %>
        </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <%= form.number_field :cooking_time,
        autofocus: true,
        autocomplete: 'cooking_time',
        placeholder: 'Cooking time in hour(s)',
        class: 'form-control'
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:cooking_time].first %>
        </p>
    <% end %>
  </div>

	<div class = "mt-2 p-2">
		<%= form.text_area :description, rows: "5",
        autofocus: true, 
        autocomplete: 'description', 
        placeholder: 'Description of the recipe', 
        class: 'form-control' 
    %>
    <% if @recipe.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe.errors[:description].first %>
        </p>
    <% end %>
  </div>

  <div class="actions d-flex justify-content-sm-between mt-4">
    <%= form.submit class: 'btn btn-dark btn-sm' %>
    <button type="button" class="btn btn-dark btn-sm px-3" data-bs-dismiss="modal">Cancel</button>
  </div>
<% end %>

app/views/recipes/form_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form" %>
<% end %>

app/views/recipes/general_shopping_list.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8 mt-4 p-2">
      <h3 class="text-center mb-5">
        Shopping List
      </h3>

      <% if @shopping_list.empty? %>
        <p class="alert alert-info">
          There is no missing food.
        </p>
      <% elsif @shopping_list.any? %>
        <div class="d-flex justify-content-between mb-3 px-5 fw-bold">
          <span>
            Amount of food items to buy: <%= @shopping_list.size %>
          </span>
          <span>
            Total value of food needed: <%= @shopping_list.sum(&:price) %>
          </span>
        </div>
        <div class="d-flex justify-content-center">
          <div class="col-md-10">
            <hr>
            <table class="table table-striped table-ligth table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Food</th>
                  <th class="w-25 text-center">Quantity</th>
                  <th class="w-25 text-center">Unit Price</th>
                </tr>
              </thead>
              <tbody>
                <% @shopping_list.each_with_index do |food, index| %>
                  <tr>
                    <td><%= index + 1 %></td>
                    <td><%= food.name %></td>
                    <td class="text-center">
                      <%= food.quantity %>
                      <%= food.measurement_unit %>
                    </td>
                    <td class="text-center"><%= food.price %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
    </div>
  </div>     
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 mt-4 p-2">
      <h3 class="text-center">
        Recipes List
      </h3>
    
      <div class="d-flex justify-content-end p-2">
        <%= link_to "New Recipe", new_recipe_path, class: "btn btn-primary", data: { turbo_frame: "remote_modal" }%>
      </div>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
        </p>
      <% elsif @recipes.empty? %>
        <p class="alert alert-info">
          No recipes added yet by this user. Please add new recipe.
        </p>
      <% end %>

      <% if @recipes.any? %>
        <% @recipes.each do |recipe| %>
          <div class="row border mb-4">
            <div class="col-4 py-3 ps-4 text-start">
              <%= link_to recipe.name, recipe_path(recipe), class: 'nav-link mb-3 fs-4 link-dark'%>
                <%= button_to "Remove", recipe_path(recipe), class: "btn btn-danger fs-5 p-1 custom-button-width", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
              </div>
            <div class="col p-2 text-start">
              <p><%= recipe.description %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render "partials/remote_modal", title: "Add New Recipe" do %>

  <%= render "form" %>
  
<% end %>

app/views/recipes/public_recipes.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-6 mt-4 p-2">
      <h1 class="text-center">Public Recipes List</h1>

      <% if @public_recipes.empty? %>
        <p class="alert alert-info">
          No public recipes added yet by any user. 
          <%= link_to 'Create one', new_recipe_path, data: { turbo_frame: "remote_modal" } %>
        </p>
      <% else %>
        <% @public_recipes.each do |public_recipe| %>
          <% public_recipe.recipes.each do |recipe| %>
            <div class="row border mb-4">
              <div class="col-4 p-3 text-start">
                <%= link_to recipe.name, recipe_path(recipe), class: 'nav-link mb-3 fs-4 link-dark' %>
                <span class="mb-3">By: <%= public_recipe.name %></span>
              </div>
              <div class="d-flex flex-column col text-end p-4">
                <span class="py-1">Total food items: <strong><%= recipe.recipe_foods.count %></strong></span>
                <span class="py-1">Total quantities: <strong><%= recipe.recipe_foods.sum(:quantity) %> </strong></span>
                <span class="py-1">Total price: 
                  <strong> 
                      <%= recipe.recipe_foods.sum do |recipe_food|
                        recipe_food.quantity * recipe_food.food.price
                      end %>
                  </strong>
                </span>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8 mt-4 p-2">
      <h1 class="text-center">
        <%= @recipe.name %>
      </h1>
      
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <div class="d-flex justify-content-between align-items-center mb-3">
        <span>
          Preparation Time:
          <%= @recipe.preparation_time %>
          <%= @recipe.preparation_time > 1 ? 'hours' : 'hour' %> 
        </span>
        <% if can? :manage, @recipe %>
          <div data-controller="recipe" class="form-check form-switch form-check-reverse">
            <%= form_with(model: @recipe) do |form| %>
              <%= form.check_box :public, class: "form-check-input",
                                  checked: @recipe.public,
                                  data: { id: @recipe.id, action: "recipe#toggle_public" } %>
              <label class="form-check-label" for="toggle">Public</label>
            <% end %>
          </div>
        <% end %>
      </div>

      <span class="d-block mb-3">
        Cooking Time:
        <%= @recipe.cooking_time %>
        <%= @recipe.cooking_time > 1 ? 'hours' : 'hour' %>
      </span>
      <span class="steps">Steps goes here...</span>

      <div class="d-flex justify-content-between align-items-center mt-3">
        <div class="add-btn">
          <%= link_to 'Generate Shopping List', general_shopping_list_path, class: 'btn btn-secondary' %>
        </div>
        <% if can? :manage, @recipe %>
          <div class="add-btn">
            <%= link_to 'Add ingredient', new_recipe_recipe_food_path(recipe_id: @recipe.id), class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>

      <hr/>
      <% if @recipe.recipe_foods.empty? %>
        <p class="no-record text-center">
          No food ingredient added to this recipe yet.
        </p>
      <% end %>

      <% if @recipe.recipe_foods.any? %>
        <table class="table table-striped table-bordered mt-2">
					<thead>
						<tr>
						  <th scope="col">#</th>
							<th scope="col">Food</th>
							<th scope="col">Quantity</th>
							<th scope="col">Value</th>
							<th scope="col" class="text-center">Actions</th>
						</tr>
					</thead>
					<tbody>
            <% @recipe.recipe_foods.each_with_index do |food_recipe, index| %>
              <tr>
                <td><%= index + 1 %></td>										
                <td><%=food_recipe.food.name %></td>
                <td>
                  <%= food_recipe.quantity.to_i %>
                  <%= food_recipe.food.measurement_unit %>
                </td>
                <td>
                  <% if food_recipe.quantity.present? && food_recipe.food.price.present? %>
                      $<%= food_recipe.quantity * food_recipe.food.price %>
                  <% else %>
                    N/A
                  <% end %>
                </td>
                <td class="d-flex justify-content-center justify-content-around">
                  <% if can? :manage, @recipe %>
                    <%= link_to 'Modify', edit_recipe_recipe_food_path(@recipe, food_recipe), class: 'btn btn-danger btn-sm' %>
                    <%= button_to "Remove", recipe_recipe_food_path(@recipe, food_recipe), class: "btn btn-danger", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
                  <% else %>
                    NA
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
			  </table>
      <% end %>
    </div>
  </div>
</div>