config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end

  resources :foods

  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'

  post '/recipe/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

  get '/general_shopping_list', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'RecipeApp', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-right" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>          
          <li class="nav-item">
            <%= link_to "Foods", foods_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Recipes", recipes_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, form_class: "nav-link" %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class='container'>
  <h1>welcome to Recipe App</h1>  
</div>