config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end

  resources :foods

  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'

  post '/recipe/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

  get '/general_shopping_list', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, class_name: 'RecipeFood', dependent: :destroy
  has_and_belongs_to_many :recipes, join_table: :recipe_foods

  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 50 }
  validates :measurement_unit, presence: true, length: { minimum: 2, maximum: 10 }
  validates :price, presence: true, numericality: { greater_than: 0, less_than: BigDecimal(10**3) },
                    format: { with: /\A\d+(?:\.\d{0,2})?\z/ }
  validates :quantity, presence: true, numericality: { greater_than: 0, less_than: 10**3 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  load_and_authorize_resource
  include FoodsHelper

  def index
    notice_message
    @foods = Food.all.where(user_id: current_user.id)
  end

  def new
    @food = Food.new
    respond_to do |format|
      format.html { render :new }
      format.js { render :new }
    end
  end

  def create
    @food = Food.new(food_params)
    @food.user = current_user
    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
        format.turbo_stream { render :new_update, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @food = Food.find(params[:id])
    respond_to do |format|
      format.html { render :edit }
      format.js { render :edit }
    end
  end

  def update
    @food = Food.find(params[:id])
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to foods_path, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
        format.turbo_stream { render :edit_update, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id])
    respond_to do |format|
      if can? :destroy, @food
        @food.destroy
        format.html { redirect_to foods_path, notice: 'Food item was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to foods_path, alert: 'Food item was not deleted.' }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
  def notice_message
    url = Rails.application.routes.recognize_path(request.referrer)
    flash.delete(:notice) unless %w[index show new edit update
                                    destroy].include?(url[:action]) && url[:controller] == 'foods'
  end
end

app/views/foods/_form.html.erb
  <div class = "p-2">
    <%= form.label :name, "Food Name:" %>
    <%= form.text_field :name,
        autofocus: true, 
        autocomplete: 'name', 
        placeholder: 'New Food Name', 
        class: 'form-control' 
    %>
    <% if @food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @food.errors[:name].first %>
        </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <%= form.label :measurement_unit, "Measurement Unit:" %>
    <%= form.text_field :measurement_unit,
        autofocus: true, 
        autocomplete: 'measurement unit', 
        placeholder: 'Measurement Unit', 
        class: 'form-control' 
    %>
    <% if @food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @food.errors[:measurement_unit].first %>
        </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <%= form.label :price, "Unit Price:" %>
    <%= form.number_field :price, step: :any,
        autofocus: true,
        autocomplete: 'price',
        placeholder: 'Unit Price',
        class: 'form-control' 
    %>
    <% if @food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @food.errors[:price].first %>
        </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <%= form.label :quantity, "Quantity:" %>
    <%= form.number_field :quantity,
        autofocus: true,
        autocomplete: 'quantity',
        placeholder: 'Quantity',
        class: 'form-control' 
    %>
    <% if @food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @food.errors[:quantity].first %>
        </p>
    <% end %>
  </div>

  <div class="actions d-flex justify-content-sm-between mt-4">
    <%= form.submit class: 'btn btn-dark btn-sm' %>
    <button type="button" class="btn btn-dark btn-sm px-3" data-bs-dismiss="modal">Cancel</button>
  </div>

app/views/foods/edit.html.erb
<%= render "partials/remote_modal", title: "Edit Food" do %>

  <%= form_with(model: @food, url: food_path(@food), local: true) do |form| %>
    <%= render "form", form: form %>
  <% end %>
  
<% end %>

app/views/foods/edit_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  
  <%= form_with(model: @food, url: food_path(@food), local: true) do |form| %>
    <%= render "form", form: form %>
  <% end %>

<% end %>

app/views/foods/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 mt-4 p-2">
      <h3 class="text-center">
        Foods List
      </h3>

      <div class="d-flex justify-content-end">
        <%= link_to 'New Food', new_food_path, class: "btn btn-primary", data: { turbo_frame: "remote_modal" } %>
      </div>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>

      <% if alert %>
        <p class="alert alert-danger">
          <%= alert %>
        </p>
      <% elsif @foods.empty? %>
        <p class="alert alert-info">
          No foods added yet by this user. Please add new food.
        </p>
      <% end %>

      <% if @foods.any? %>
        <hr>
        <table class="table table-striped table-ligth table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th class="w-25">Food</th>
              <th class="text-center">Measurement Unit</th>
              <th class="text-center">Unit Price</th>
              <th class="text-center">Quantity</th>
              <th class="text-center">Action</th>
            </tr>
          </thead>
          <tbody>
            <% @foods.each_with_index do |food, index| %>
              <tr>
                <td><%= index + 1 %></td>
                <td><%= food.name %></td>
                <td class="text-center"><%= food.measurement_unit %></td>
                <td class="text-center"><%= food.price %></td>
                <td class="text-center"><%= food.quantity %></td>
                <td class="d-flex justify-content-center justify-content-around" >
                  <span> <%= link_to "Modify", edit_food_path(food), class: "btn btn-danger", data: { turbo_frame: "remote_modal" }%> </span>
                  <span> <%= button_to "Remove", food_path(food), class: "btn btn-danger", method: :delete, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %></span>                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>     
</div>

app/views/foods/new.html.erb
<%= render "partials/remote_modal", title: "Add New Food" do %>

  <%= form_with(model: @food, url: foods_path, local: true) do |form| %>
    <%= render "form", form: form %>
  <% end %>
  
<% end %>

app/views/foods/new_update.turbo_stream.erb
<%= turbo_stream.update "remote_modal_body" do %>
  
  <%= form_with(model: @food, url: foods_path, local: true) do |form| %>
    <%= render "form", form: form %>
  <% end %>

<% end %>