config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :recipes do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end

  resources :foods

  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'

  post '/recipe/:id/toggle_public', to: 'recipes#toggle_public', as: 'toggle_public'

  get '/general_shopping_list', to: 'recipes#general_shopping_list', as: 'general_shopping_list'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, class_name: 'Recipe', foreign_key: 'recipe_id'
  belongs_to :food, class_name: 'Food', foreign_key: 'food_id'

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :recipe_id, presence: true, uniqueness: { scope: :food_id }
  validates :food_id, presence: true, uniqueness: { scope: :recipe_id }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index; end

  def show; end

  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all.where(user_id: current_user.id)
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @recipe = Recipe.find(params[:recipe_food][:recipe_id])

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_path(@recipe), notice: 'Recipe Food was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        @foods = Food.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(@recipe_food.recipe_id)
    @foods = Food.all
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = Recipe.find(@recipe_food.recipe_id)

    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_path(@recipe_food.recipe_id), notice: 'Recipe Food was successfully updated.' }
        format.json { render :show, status: :created, location: @recipe_food }
      else
        @foods = Food.all
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe_food.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_path, notice: 'Recipe Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :recipe_id, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_edit.html.erb
<%= form_with(model: @recipe_food, url: recipe_recipe_food_path, local: true) do |form| %>
  <div class = "p-2">
    <label for="food_id" class="form-label">Food</label>
    <%= form.hidden_field :recipe_id, value: @recipe.id %>
    <%= form.collection_select :food_id, @foods, :id, :name, { prompt: '.. Select a Food ..' }, id: 'food-select'%>
    
    <% if @recipe_food.errors.any? %>
      <p class="text-danger mb-0">
        <%= @recipe_food.errors[:food_id].first %>
      </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <label for="quantity" class="form-label">Quantity</label>
    <%= form.number_field :quantity,
      autofocus: true,
      autocomplete: 'quantity',
      placeholder: 'Quantity in grams',
      class: 'form-control'
    %>
    <% if @recipe_food.errors.any? %>
      <p class="text-danger mb-0">
        <%= @recipe_food.errors[:quantity].first %>
      </p>
    <% end %>
  </div>

  <div class="actions text-center mt-4">
    <%= form.submit 'Save', class: 'btn btn-dark btn-sm px-4' %>
    <%= link_to 'Cancel', recipe_path(@recipe), class: "btn btn-dark btn-sm px-3" %>
  </div>
<% end %>

app/views/recipe_foods/_new.html.erb
<%= form_with(model: @recipe_food, url: recipe_recipe_foods_path, local: true) do |form| %>
  <div class = "mt-4 p-2">
    <%= form.hidden_field :recipe_id, value: @recipe.id %>
    <%= form.collection_select :food_id, @foods, :id, :name, { prompt: '.. Select a Food ..' }, id: 'food-select'%>

    <% if @recipe_food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe_food.errors[:food_id].first %>
        </p>
    <% end %>
  </div>

  <div class = "mt-2 p-2">
    <%= form.number_field :quantity,
        autofocus: true,
        autocomplete: 'quantity',
        placeholder: 'Enter quantity',
        class: 'form-control'
    %>
    <% if @recipe_food.errors.any? %>
        <p class="text-danger mb-0">
          <%= @recipe_food.errors[:quantity].first %>
        </p>
    <% end %>
  </div>

  <div class="actions text-center mt-4">
    <%= form.submit 'Add', class: 'btn btn-dark btn-sm  px-4' %>
    <%= link_to 'Cancel', recipe_path(@recipe), class: "btn btn-dark btn-sm px-3" %>
  </div>
<% end %>

app/views/recipe_foods/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-4 mt-5 p-2 border shadow-lg bg-white rounded">
      <h4 class="text-center"><%= @recipe.name %></h4>
      <h5 class="text-center">
          Edit Ingredient
      </h5>

      <%= render 'edit' %>

    </div>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-4 mt-5 p-2 border shadow-lg bg-white rounded">
      <h4 class="text-center"><%= @recipe.name %></h4>
      <h5 class="text-center">
          Add Ingredient
      </h5>

      <% unless @foods.empty? %>
        <%= render 'new' %>
      <% else %>
        <p class="text-center mt-4">
          No foods available. Please add a food first. <br>
          <%= link_to 'Add a Food', new_food_path, data: { turbo_frame: "remote_modal" } %>
        </p>
        <div class="actions text-end mt-4">
          <%= link_to 'Cancel', recipe_path(@recipe), class: "btn btn-dark btn-sm px-3" %>
        </div>
      <% end %>

    </div>
  </div>
</div>